version: '3'
services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      GRPC_SERVER_ADDRESS: "0.0.0.0:9090"
      PROMETHEUS_METRIC_ADDRESS: "0.0.0.0:9091"
      DB_SOURCE: postgresql://root:1qaz@postgres:5432/broker?sslmode=disable

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9093:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9094:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1qaz
      POSTGRES_DB: broker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_URI: "postgres:5432/broker?sslmode=disable"
      DATA_SOURCE_USER: "root"
      DATA_SOURCE_PASS: "1qaz"

volumes:
  prometheus_data:
  grafana_data:
  postgres_data: